### PR TITLE
Suggested Histogrammar

### PR DESCRIPTION
**Pull request by jpivarski**
I really should bring this up, since we're discussing histograms. Histogrammar would provide interactivity with more than just ROOT: it's supposed to be an exchange format and data analyst's API for aggregation in general. It was originally designed for Spark's parallelism, it's been integrated into ROOT (filling TTrees and providing drawable ROOT objects), and I'm now working on aggregation of quantities on a GPU, for plotting intermediate quantities in processes that run on the GPU (debugging).

### CODE REVIEW

**Comment by jpivarski** [comment]
I'm beginning to agree with Oliver: this is a cumbersome way to edit a document.

**Comment by jpata** [comment]
About histogrammar: to me, the common interface should be something from StatsBase. Do you have a proposed way of interfacing it with the ROOT classes? 

About editing: No strong feelings here, though I've had good experiences with flat markdown documents (some people use it for slides even) and bad with TWiki/github wiki pages.

**Comment by jpivarski** [comment]
The idea of Histogrammar is that it interfaces with everything to serve as a bridge. More concretely, it's a suite of 20 class APIs that are identical across languages; different implementations can fill them different ways (back-ends) and/or plot them different ways (front-ends).

histogrammar-python currently has a custom ROOT back-end, which fills from TTrees (at the speed of C++, thanks to JIT-compilation through Cling) and it has a custom ROOT front-end, which turns recognized combinations of classes into drawable ROOT objects. For instance, "binned counts" (Bin(Count())) become TH1 objects, "binned mean+standard deviations" (Bin(Deviate())) become TProfile objects, "binned binned counts" (Bin(Bin(Count()))) become TH2, "ratios of binned counts" (Fraction(Bin(Count()))) become TEfficiency, etc.

I don't have a reference for the TTree filling with Cling-acceleration because it's too new. (I could send you a PDF of slides that I showed yesterday.) But the ROOT plotting interface has a tutorial:

http://histogrammar.org/docs/tutorials/python-pyroot/

The same site has tutorials for usage in Spark, Matplotlib, Bokeh, and others.

There was an attempt many years ago (called AIDA) to cross-language standardize histogram interfaces, but they described a few plot types with a lot of bells and whistles. I'm trying a more UNIX-y approach of making a suite of single-purpose tools that can be composed (with attention to parallelizability and a common JSON format).

As I said above, the Julia version (half-done) will certainly output to StatsBase as a front-end, creating every type of aggregated data in the StatsBase library. I'm also planning to output to Gadfly.

About editing: markdown is great, but the pull-request cycle is a bit overkill for editing text. I was thinking more like Google Docs (forsaking version control for rapidity). Our conversation about Histogrammar is now in three places: the markdown document we're editing, the commit message, and this comments discussion. I don't know if these comments will go away when the pull request is done, or at least be hard to discover. It's a rather stringy process.

**Comment by jpata** [comment]
Right. I'm all on board for histogrammar. What you're essentially proposing is that the TTree interface needs to expose the branches in such a way that the anonymous functions can access it. This is more an event model question in my understanding. Perhaps you can elaborate on your proposal a bit more, how should we take this into account when designing the julia ROOT API? 

These comments will always be available unless github folds. They are clearly linked to an idea or an issue, versioned, have code formatting, public. I'd much rather prefer this. The fact that every julia technical discussion is on the github issues/PR-s page is a big plus IMHO.

**Comment by jpivarski** [comment]
Oh, sorry: I misunderstood. The "how" of integrating it depends on the structure of the rest of the API. I need to sit down and try the existing APIs to understand that. Histogrammar probably won't be in the first round of decisions made about the API: that would be more fundamental things like (1) shared process vs separate process, (2) automatic wrapping of ROOT classes vs call them inside quoted strings (the Cxx.jl approach) or maybe misinterpreted Julia ASTs (part of my earlier suggestion). Question (2.5) is how to harmonize the OOP-like dot notation expected in ROOT with Julia's "function name first" multiple dispatch.

In a later round of questions, we'd be asking whether TH1, TProfile, etc. should directly feed into StatsBase, Gadfly, etc. or if Histogrammar would be an intermediary (ROOT fills Histogrammar objects, Histogrammar objects fill StatsBase, Gadfly, etc.). I don't see a reason not to do both, other than the effort required. If there are N ways to aggregate and M ways to plot, you either have to wire up N*M interfaces manually or N+M interfaces if you have an intermediary.

**Comment by jpata** [comment]
OK, now I see your point. You're proposing to use Histogrammar.jl as the backend for all histogramming, so that would be sort of the "common interface" for histograms.
It's worth considering IMHO. A while back, I wrote my own histogram classes (on top of StatsBase) for julia: https://github.com/jpata/Histograms.jl, but it's of course better to use a package that is developed by more than one person.

**Pull request merged**
